name: Terraform Validate

run-name: ${{ github.actor }} - ${{ github.ref_name }}

on:
    pull_request:
      branches: ["main"]
  
    workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.4

    - name: Validate Terraform
      id: validate
      run: terraform validate

    - name: Check Lock File
      id: check_lock
      run: |
        if [ ! -f terraform.lock.hcl ]; then
          echo "Lock file not found!"
          exit 1
        fi
        echo "Lock file found and verified."
